### PR TITLE
Support additional settings: server encoding, server collation, server variables

### PR DESCRIPTION
**Pull request by kiakimov**

### CODE REVIEW

**Comment by kiakimov** [comment]
Hi @michaelruocco, what do you think about this PR?

**Comment by michaelruocco** [comment]
Hi Kiakimov, apologies for the delay. Generally it looks okay to me. I would potentially like to refactor out the validation logic into separate classes to keep a cleaner separation of concerns. I have been pretty busy at work so I have not had time to look in detail, but I can accept it for now and then look at reworking it later.

Once I have done that I will release a new version, you should be able to build a new version of the plugin locally for now though?

**Comment by kiakimov** [comment]
Sure, we already use local build.
Many thanks!

**Comment by michaelruocco** [comment]
@kiakimov I have pushed some changes to attempt to clean up some of the code. The tests you added are still passing so I am sure it should be okay, but do you want to try doing a local build with the changes. Once you are happy I will release a new version if that is okay with you?

**Comment by michaelruocco** [comment]
@kiakimov also, if you have some example config that you have used for setting server variables and charsets can you send over a snippet so I can add an example to the readme file.

Thanks,

**Comment by kiakimov** [comment]
Hi @michaelruocco 
1) Ive tried new local build - it is working and looks good to go
2) sample config
```
embeddedMysql {
    url = 'jdbc:mysql://localhost:3306/my'
    username = 'user'
    password = 'user'
    version  = 'v5_6_24'
    serverCharset = 'utf8'
    serverCollate = 'utf8_general_ci' 
    serverVars = ['explicit_defaults_for_timestamp' : true]
}
```

**Comment by michaelruocco** [comment]
Thanks @kiakimov I have added some detail explaining the features you added to the readme and have just released version 2.1.5. It should be on maven central in the next half hour or so. Thanks again for the contribution!

**Pull request merged**
