### PR TITLE
Multiply schema support

### PR DESCRIPTION
**Pull request by kiakimov**

### CODE REVIEW

**Comment by kiakimov** [comment]
please review, this is additional schemas support
plugin can be configured as
```
url = jdbc:mysql://xxxx/schema1
schema = schema2, schema3
```
or even
```
url = jdbc:mysql://xxxx/schema1
schema = schema1, schema2
```
or without schema property (as usual)

**Comment by michaelruocco** [comment]
@kiakimov generally this looks fine, would you mind updating the readme as well so that in includes an example that shows how to configure using your new schema option under a new heading? Other than that it looks fine and I am happy to merge. Thanks for contributing again!

**Comment by kiakimov** [comment]
Hey @michaelruocco I just force pushed readme changes, please review. Thank you!

**Comment by michaelruocco** [comment]
@kiakimov I have just merged this change and released to maven central as version 2.1.8. Alternatively you can pull it from: https://plugins.gradle.org/plugin/com.github.michaelruocco.embedded-mysql-plugin

It should be available shortly, thanks again for the contribution.

**Pull request merged**
